import { IconType } from "react-icons";

import {
  HiOutlineRocketLaunch,
  HiOutlineChartBarSquare,
  HiOutlineBolt,
  HiOutlineShieldCheck,
  HiOutlineCpuChip,
  HiOutlineGlobeAlt,
  HiOutlineClock,
  HiOutlineUsers,
  HiOutlineEnvelope,
  HiOutlinePhone,
  HiOutlineMapPin,
  HiOutlineCheck,
  HiOutlineXMark,
  HiOutlineArrowTrendingUp,
  HiOutlinePuzzlePiece,
  HiOutlineAdjustmentsHorizontal,
  HiOutlineBellAlert,
  HiOutlineDocumentChartBar,
  HiOutlineServerStack,
  HiOutlineCommandLine,
  HiOutlineLightBulb,
  HiOutlineHeart,
  HiOutlineStar,
  HiOutlineBeaker,
  HiOutlineEye,
  HiOutlineCubeTransparent,
  HiOutlineSquares2X2,
} from "react-icons/hi2";

export const iconLibrary: Record<string, IconType> = {
  rocket: HiOutlineRocketLaunch,
  chart: HiOutlineChartBarSquare,
  bolt: HiOutlineBolt,
  shield: HiOutlineShieldCheck,
  cpu: HiOutlineCpuChip,
  globe: HiOutlineGlobeAlt,
  clock: HiOutlineClock,
  users: HiOutlineUsers,
  envelope: HiOutlineEnvelope,
  phone: HiOutlinePhone,
  mapPin: HiOutlineMapPin,
  check: HiOutlineCheck,
  xMark: HiOutlineXMark,
  trending: HiOutlineArrowTrendingUp,
  puzzle: HiOutlinePuzzlePiece,
  adjustments: HiOutlineAdjustmentsHorizontal,
  bell: HiOutlineBellAlert,
  document: HiOutlineDocumentChartBar,
  server: HiOutlineServerStack,
  command: HiOutlineCommandLine,
  lightbulb: HiOutlineLightBulb,
  heart: HiOutlineHeart,
  star: HiOutlineStar,
  beaker: HiOutlineBeaker,
  eye: HiOutlineEye,
  cube: HiOutlineCubeTransparent,
  grid: HiOutlineSquares2X2,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
